version: "2"

services:
  mongo-db:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    network_mode: host
  vscode:
    image: nathanlenas/angulardev:latest
    container_name: vscode-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - $HOME/.config:/home/coder/.config
      - ../../Project/:/home/coder/project

